// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjW0DkIJfqBnSWVuDAm83hT-MIxjyqk8',
    appId: '1:57024455215:web:703388476a4555563b9cda',
    messagingSenderId: '57024455215',
    projectId: 'projet-pfe-5a26a',
    authDomain: 'projet-pfe-5a26a.firebaseapp.com',
    databaseURL: 'https://projet-pfe-5a26a-default-rtdb.firebaseio.com',
    storageBucket: 'projet-pfe-5a26a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KddeQjwtDVv1tZidIHBrOE4vx8eKBUw',
    appId: '1:57024455215:android:2af0d66aeec864be3b9cda',
    messagingSenderId: '57024455215',
    projectId: 'projet-pfe-5a26a',
    databaseURL: 'https://projet-pfe-5a26a-default-rtdb.firebaseio.com',
    storageBucket: 'projet-pfe-5a26a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQmootzdaZEFKX-AKNk9DX4fMJhm_Jcfo',
    appId: '1:57024455215:ios:e7431ace3b9399b63b9cda',
    messagingSenderId: '57024455215',
    projectId: 'projet-pfe-5a26a',
    databaseURL: 'https://projet-pfe-5a26a-default-rtdb.firebaseio.com',
    storageBucket: 'projet-pfe-5a26a.firebasestorage.app',
    iosBundleId: 'com.example.appPfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQmootzdaZEFKX-AKNk9DX4fMJhm_Jcfo',
    appId: '1:57024455215:ios:e7431ace3b9399b63b9cda',
    messagingSenderId: '57024455215',
    projectId: 'projet-pfe-5a26a',
    databaseURL: 'https://projet-pfe-5a26a-default-rtdb.firebaseio.com',
    storageBucket: 'projet-pfe-5a26a.firebasestorage.app',
    iosBundleId: 'com.example.appPfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfjW0DkIJfqBnSWVuDAm83hT-MIxjyqk8',
    appId: '1:57024455215:web:73994593b1e230863b9cda',
    messagingSenderId: '57024455215',
    projectId: 'projet-pfe-5a26a',
    authDomain: 'projet-pfe-5a26a.firebaseapp.com',
    databaseURL: 'https://projet-pfe-5a26a-default-rtdb.firebaseio.com',
    storageBucket: 'projet-pfe-5a26a.firebasestorage.app',
  );
}
